local env = getfenv and getfenv(0) or _G

local services = {
	"Players",
	"RunService",
	"TweenService",
	"UserInputService",
	"HttpService",
	"ReplicatedStorage",
	"ReplicatedFirst",
	"ServerStorage",
	"ServerScriptService",
	"StarterGui",
	"StarterPack",
	"StarterPlayer",
	"Workspace",
	"Lighting",
	"SoundService",
	"CollectionService",
	"ContextActionService",
	"GuiService",
	"PathfindingService",
	"PhysicsService",
	"MarketplaceService",
	"BadgeService",
	"GroupService",
	"DataStoreService",
	"MemoryStoreService",
	"MessagingService",
	"InsertService",
	"ContentProvider",
	"LocalizationService",
	"TeleportService",
	"TextService",
	"TextChatService",
	"Teams",
	"Chat",
	"Debris",
	"Stats",
	"HapticService",
	"VRService",
	"GamepadService",
	"TouchInputService",
	"VirtualInputManager",
	"VirtualUser",
	"AnimationClipProvider",
	"KeyframeSequenceProvider",
	"AssetService",
	"AvatarEditorService",
	"AvatarCreationService",
	"CoreGui",
	"NetworkSettings",
	"UserGameSettings",
	"ProximityPromptService",
	"LogService",
	"PolicyService",
	"SocialService",
	"CaptureService",
	"SharedTableRegistry",
	"GeometryService",
	"MaterialService",
	"TaskScheduler",
	"TimerService",
	"StreamingService",
	"JointsService",
	"ScriptContext",
	"AvatarChatService",
	"VoiceChatService",
	"FaceAnimatorService",
	"NotificationService",
	"GamePassService",
	"PointsService",
	"FriendService",
	"AchievementService",
	"AdService",
	"AnalyticsService",
	"ExperienceNotificationService",
	"PlayerEmulatorService",
}

for _, name in ipairs(services) do
	local ok, svc = pcall(game.GetService, game, name)
	if ok and svc then
		env[name] = svc
	end
end
